version: 2

project_name: sql-reviewer

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - "386"
      - amd64
      - arm
      - arm64
    goarm:
      - "6"
      - "7"
    ignore:
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64
    main: ./main.go
    binary: sql-reviewer
    ldflags:
      - -s -w -X github.com/nsxbet/sql-reviewer-cli/cmd.version={{.Version}} -X github.com/nsxbet/sql-reviewer-cli/cmd.commit={{.Commit}} -X github.com/nsxbet/sql-reviewer-cli/cmd.date={{.Date}}

archives:
  - formats: [tar.gz]
    name_template: >-
      {{ .ProjectName }}_ {{- title .Os }}_ {{- if eq .Arch "amd64" }}x86_64 {{- else if eq .Arch "arm64" }}arm64 {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        formats: [zip]
    files:
      - README.md
      - LICENSE*
      - CHANGELOG*
      - docs/*
      - examples/*

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - '^chore:'
  groups:
    - title: 'New Features'
      regexp: '^.*?feat(\(.+\))??!?:.+$'
      order: 0
    - title: 'Bug Fixes'
      regexp: '^.*?fix(\(.+\))??!?:.+$'
      order: 1
    - title: 'Performance Improvements'
      regexp: '^.*?perf(\(.+\))??!?:.+$'
      order: 2
    - title: 'Documentation Updates'
      regexp: '^.*?docs(\(.+\))??!?:.+$'
      order: 3
    - title: 'Dependency Updates'
      regexp: '^.*?deps(\(.+\))??!?:.+$'
      order: 4
    - title: 'Other Changes'
      order: 999
