id: sql-review-prod
rules:
  - type: not.implemented.rule
    level: ERROR
    engine: MYSQL
  - type: engine.mysql.use-innodb
    level: ERROR
    engine: MYSQL
  - type: table.require-pk
    level: ERROR
    engine: MYSQL
  - type: table.require-pk
    level: ERROR
    engine: POSTGRES
  - type: table.no-foreign-key
    level: ERROR
    engine: MYSQL
  - type: table.no-foreign-key
    level: ERROR
    engine: POSTGRES
  - type: table.drop-naming-convention
    level: ERROR
    payload:
      format: _del$
    engine: MYSQL
  - type: table.drop-naming-convention
    level: ERROR
    payload:
      format: _del$
    engine: POSTGRES
  - type: table.disallow-partition
    level: ERROR
    engine: MYSQL
  - type: table.disallow-partition
    level: ERROR
    engine: POSTGRES
  - type: table.disallow-trigger
    level: ERROR
    engine: MYSQL
  - type: table.comment
    level: ERROR
    payload:
      required: true
      maxLength: 64
    engine: MYSQL
  - type: table.comment
    level: ERROR
    payload:
      required: true
      maxLength: 64
    engine: POSTGRES
  - type: table.no-duplicate-index
    level: WARNING
    engine: MYSQL
  - type: table.text-fields-total-length
    level: WARNING
    payload:
      number: 1000
    engine: MYSQL
  - type: table.disallow-set-charset
    level: WARNING
    engine: MYSQL
  - type: table.disallow-ddl
    level: WARNING
    engine: MYSQL
  - type: table.disallow-dml
    level: WARNING
    engine: MYSQL
  - type: table.limit-size
    level: WARNING
    payload:
      number: 10000000
    engine: MYSQL
  - type: table.require-charset
    level: WARNING
    engine: MYSQL
  - type: table.require-collation
    level: WARNING
    engine: MYSQL
  - type: statement.select.no-select-all
    level: ERROR
    engine: MYSQL
  - type: statement.select.no-select-all
    level: ERROR
    engine: POSTGRES
  - type: statement.where.require.select
    level: ERROR
    engine: MYSQL
  - type: statement.where.require.select
    level: ERROR
    engine: POSTGRES
  - type: statement.where.require.update-delete
    level: ERROR
    engine: MYSQL
  - type: statement.where.require.update-delete
    level: ERROR
    engine: POSTGRES
  - type: statement.where.no-leading-wildcard-like
    level: ERROR
    engine: MYSQL
  - type: statement.where.no-leading-wildcard-like
    level: ERROR
    engine: POSTGRES
  - type: statement.disallow-commit
    level: ERROR
    engine: MYSQL
  - type: statement.disallow-commit
    level: ERROR
    engine: POSTGRES
  - type: statement.disallow-on-del-cascade
    level: ERROR
    engine: POSTGRES
  - type: statement.disallow-rm-tbl-cascade
    level: ERROR
    engine: POSTGRES
  - type: statement.disallow-limit
    level: WARNING
    engine: MYSQL
  - type: statement.disallow-order-by
    level: ERROR
    engine: MYSQL
  - type: statement.merge-alter-table
    level: ERROR
    engine: MYSQL
  - type: statement.merge-alter-table
    level: ERROR
    engine: POSTGRES
  - type: statement.insert.must-specify-column
    level: ERROR
    engine: MYSQL
  - type: statement.insert.must-specify-column
    level: ERROR
    engine: POSTGRES
  - type: statement.insert.disallow-order-by-rand
    level: ERROR
    engine: MYSQL
  - type: statement.insert.disallow-order-by-rand
    level: ERROR
    engine: POSTGRES
  - type: statement.insert.row-limit
    level: WARNING
    payload:
      number: 1000
    engine: MYSQL
  - type: statement.insert.row-limit
    level: WARNING
    payload:
      number: 1000
    engine: POSTGRES
  - type: statement.affected-row-limit
    level: WARNING
    payload:
      number: 1000
    engine: MYSQL
  - type: statement.affected-row-limit
    level: WARNING
    payload:
      number: 1000
    engine: POSTGRES
  - type: statement.dml-dry-run
    level: ERROR
    engine: MYSQL
  - type: statement.dml-dry-run
    level: ERROR
    engine: POSTGRES
  - type: statement.disallow-add-column-with-default
    level: WARNING
    engine: POSTGRES
  - type: statement.add-check-not-valid
    level: WARNING
    engine: POSTGRES
  - type: statement.disallow-add-not-null
    level: WARNING
    engine: POSTGRES
  - type: statement.select-full-table-scan
    level: ERROR
    engine: MYSQL
  - type: statement.create-specify-schema
    level: WARNING
    engine: POSTGRES
  - type: statement.check-set-role-variable
    level: WARNING
    engine: POSTGRES
  - type: statement.disallow-using-filesort
    level: WARNING
    engine: MYSQL
  - type: statement.disallow-using-temporary
    level: WARNING
    engine: MYSQL
  - type: statement.where.no-equal-null
    level: WARNING
    engine: MYSQL
  - type: statement.where.disallow-functions-and-calculations
    level: WARNING
    engine: MYSQL
  - type: statement.query.minimum-plan-level
    level: WARNING
    payload:
      required: true
      maxLength: 64
    engine: MYSQL
  - type: statement.where.maximum-logical-operator-count
    level: WARNING
    payload:
      number: 10
    engine: MYSQL
  - type: statement.maximum-limit-value
    level: WARNING
    payload:
      number: 1000
    engine: MYSQL
  - type: statement.maximum-limit-value
    level: WARNING
    payload:
      number: 1000
    engine: POSTGRES
  - type: statement.maximum-join-table-count
    level: WARNING
    payload:
      number: 10
    engine: MYSQL
  - type: statement.maximum-statements-in-transaction
    level: WARNING
    payload:
      number: 10
    engine: MYSQL
  - type: statement.join-strict-column-attrs
    level: WARNING
    engine: MYSQL
  - type: statement.disallow-mix-in-ddl
    level: WARNING
    engine: MYSQL
  - type: statement.disallow-mix-in-ddl
    level: WARNING
    engine: POSTGRES
  - type: statement.disallow-mix-in-dml
    level: WARNING
    engine: MYSQL
  - type: statement.disallow-mix-in-dml
    level: WARNING
    engine: POSTGRES
  - type: statement.max-execution-time
    level: ERROR
    engine: MYSQL
  - type: statement.require-algorithm-option
    level: ERROR
    engine: MYSQL
  - type: statement.require-lock-option
    level: ERROR
    engine: MYSQL
  - type: naming.fully-qualified
    level: WARNING
    engine: POSTGRES
  - type: naming.table
    level: WARNING
    payload:
      format: "^[a-z]+(_[a-z]+)*$"
      maxLength: 63
    engine: MYSQL
  - type: naming.table
    level: WARNING
    payload:
      format: "^[a-z]+(_[a-z]+)*$"
      maxLength: 63
    engine: POSTGRES
  - type: naming.column
    level: WARNING
    payload:
      format: "^[a-z]+(_[a-z]+)*$"
      maxLength: 63
    engine: MYSQL
  - type: naming.column
    level: WARNING
    payload:
      format: "^[a-z]+(_[a-z]+)*$"
      maxLength: 63
    engine: POSTGRES
  - type: naming.index.uk
    level: WARNING
    payload:
      format: "^$|^uk_{{table}}_{{column_list}}$"
      maxLength: 63
    engine: MYSQL
  - type: naming.index.uk
    level: WARNING
    payload:
      format: "^$|^uk_{{table}}_{{column_list}}$"
      maxLength: 63
    engine: POSTGRES
  - type: naming.index.pk
    level: WARNING
    payload:
      format: "^$|^pk_{{table}}_{{column_list}}$"
      maxLength: 63
    engine: POSTGRES
  - type: naming.index.idx
    level: WARNING
    payload:
      format: "^$|^idx_{{table}}_{{column_list}}$"
      maxLength: 63
    engine: MYSQL
  - type: naming.index.idx
    level: WARNING
    payload:
      format: "^$|^idx_{{table}}_{{column_list}}$"
      maxLength: 63
    engine: POSTGRES
  - type: naming.index.fk
    level: WARNING
    payload:
      format: >-
        ^$|^fk_{{referencing_table}}_{{referencing_column}}_{{referenced_table}}_{{referenced_column}}$
      maxLength: 63
    engine: MYSQL
  - type: naming.index.fk
    level: WARNING
    payload:
      format: >-
        ^$|^fk_{{referencing_table}}_{{referencing_column}}_{{referenced_table}}_{{referenced_column}}$
      maxLength: 63
    engine: POSTGRES
  - type: naming.column.auto-increment
    level: WARNING
    payload:
      format: ^id$
      maxLength: 63
    engine: MYSQL
  - type: naming.identifier.no-keyword
    level: WARNING
    engine: MYSQL
  - type: column.required
    level: WARNING
    payload:
      list:
        - id
        - created_ts
        - updated_ts
        - creator_id
        - updater_id
    engine: MYSQL
  - type: column.required
    level: WARNING
    payload:
      list:
        - id
        - created_ts
        - updated_ts
        - creator_id
        - updater_id
    engine: POSTGRES
  - type: column.type-disallow-list
    level: ERROR
    payload:
      list:
        - JSON
    engine: MYSQL
  - type: column.type-disallow-list
    level: ERROR
    payload:
      list:
        - JSON
    engine: POSTGRES
  - type: column.no-null
    level: WARNING
    engine: MYSQL
  - type: column.no-null
    level: WARNING
    engine: POSTGRES
  - type: column.disallow-change-type
    level: ERROR
    engine: MYSQL
  - type: column.disallow-change-type
    level: ERROR
    engine: POSTGRES
  - type: column.disallow-drop-in-index
    level: ERROR
    engine: MYSQL
  - type: column.set-default-for-not-null
    level: ERROR
    engine: MYSQL
  - type: column.disallow-change
    level: ERROR
    engine: MYSQL
  - type: column.disallow-changing-order
    level: ERROR
    engine: MYSQL
  - type: column.auto-increment-must-integer
    level: ERROR
    engine: MYSQL
  - type: column.disallow-set-charset
    level: ERROR
    engine: MYSQL
  - type: column.auto-increment-must-unsigned
    level: ERROR
    engine: MYSQL
  - type: column.comment
    level: ERROR
    payload:
      required: true
      maxLength: 64
    engine: MYSQL
  - type: column.comment
    level: ERROR
    payload:
      required: true
      maxLength: 64
    engine: POSTGRES
  - type: column.maximum-character-length
    level: WARNING
    payload:
      number: 20
    engine: MYSQL
  - type: column.maximum-character-length
    level: WARNING
    payload:
      number: 20
    engine: POSTGRES
  - type: column.maximum-varchar-length
    level: WARNING
    payload:
      number: 2560
    engine: MYSQL
  - type: column.auto-increment-initial-value
    level: WARNING
    payload:
      number: 1
    engine: MYSQL
  - type: column.current-time-count-limit
    level: WARNING
    payload:
      number: 1000
    engine: MYSQL
  - type: column.require-default
    level: WARNING
    engine: MYSQL
  - type: column.require-default
    level: WARNING
    engine: POSTGRES
  - type: column.default-disallow-volatile
    level: WARNING
    engine: POSTGRES
  - type: column.require-charset
    level: WARNING
    engine: MYSQL
  - type: column.require-collation
    level: WARNING
    engine: MYSQL
  - type: schema.backward-compatibility
    level: WARNING
    engine: MYSQL
  - type: schema.backward-compatibility
    level: WARNING
    engine: POSTGRES
  - type: database.drop-empty-database
    level: ERROR
    engine: MYSQL
  - type: index.no-duplicate-column
    level: ERROR
    engine: MYSQL
  - type: index.no-duplicate-column
    level: ERROR
    engine: POSTGRES
  - type: index.type-no-blob
    level: ERROR
    engine: MYSQL
  - type: index.pk-type-limit
    level: ERROR
    engine: MYSQL
  - type: index.key-number-limit
    level: WARNING
    payload:
      number: 5
    engine: MYSQL
  - type: index.key-number-limit
    level: WARNING
    payload:
      number: 5
    engine: POSTGRES
  - type: index.total-number-limit
    level: WARNING
    payload:
      number: 5
    engine: MYSQL
  - type: index.total-number-limit
    level: WARNING
    payload:
      number: 5
    engine: POSTGRES
  - type: index.primary-key-type-allowlist
    level: ERROR
    payload:
      list:
        - SERIAL
        - BIGSERIAL
        - INT
        - BIGINT
    engine: MYSQL
  - type: index.primary-key-type-allowlist
    level: ERROR
    payload:
      list:
        - SERIAL
        - BIGSERIAL
        - INT
        - BIGINT
    engine: POSTGRES
  - type: index.create-concurrently
    level: WARNING
    engine: POSTGRES
  - type: index.type-allow-list
    level: WARNING
    payload:
      list:
        - BTREE
        - HASH
    engine: MYSQL
  - type: system.charset.allowlist
    level: ERROR
    payload:
      list:
        - utf8mb4
    engine: MYSQL
  - type: system.charset.allowlist
    level: ERROR
    payload:
      list:
        - utf8mb4
    engine: POSTGRES
  - type: system.collation.allowlist
    level: ERROR
    payload:
      list:
        - utf8mb4_0900_ai_ci
    engine: MYSQL
  - type: system.collation.allowlist
    level: ERROR
    payload:
      list:
        - utf8mb4_0900_ai_ci
    engine: POSTGRES
  - type: system.comment.length
    level: WARNING
    payload:
      number: 64
    engine: POSTGRES
  - type: system.procedure.disallow-create
    level: WARNING
    engine: MYSQL
  - type: system.event.disallow-create
    level: WARNING
    engine: MYSQL
  - type: system.view.disallow-create
    level: WARNING
    engine: MYSQL
  - type: system.function.disallow-create
    level: WARNING
    engine: MYSQL
  - type: system.function.disallowed-list
    level: WARNING
    payload:
      list:
        - RAND
        - UUID
        - SLEEP
    engine: MYSQL
  - type: statement.add-foreign-key-not-valid
    level: WARNING
    engine: POSTGRES
  - type: statement.non-transactional
    level: WARNING
    engine: POSTGRES
  - type: statement.object-owner-check
    level: ERROR
    engine: POSTGRES
